pretranslate:
  segments:
    ignore_frontmatter_keys:
    - "layout"
    - "title"
    - "description"
    - "hero"
    - "authors"
    - "date"
    - "updated"
    - "tags"
    
        
    ignore_patterns:
      - !ruby//regexp  /^[A-Z]{1}[a-z]{3}$/
